py-mine/PyMine

- src/types/buffer.py
Resolves #49 (Finish Buffer.unpack_packet())
> 49 unpack packet

- requirements.txt
- src/logic/lan_support.py
- src/server.py
Resolves #46. All logic for login and status packets have been added. Support for compression and encryption has also been added. Logic to unpack packets automatically has been put in place, as well as other helpful things (like the share) which will assist in further logic code.
> Basic Server

- requirements.txt
- src/data/config.py
- src/logic/login.py
- src/server.py
- src/types/buffer.py
- src/util/encryption.py
- src/util/logging.py
- src/util/share.py
Comments, better + clearer code, etc... NOT done to packets, although pretty much everything else was looked over and cleaned up. Resolves #95.
> Cleanup stuff

- src/data/config.py
- src/server.py
- src/util/data_gen.py
Finish packet dumping/info, ability to specify multiple or one states to dump packets for. All in src/util/data_gen.py. Resolves #111.
> 111 update dev cmds

- src/data/packet_map.py
- src/logic/login.py
- src/logic/status.py
- src/server.py
- src/types/buffer.py
- src/types/packet.py
- src/types/packets/handshaking/handshake.py
- src/types/packets/handshaking/legacy_ping.py
- src/types/packets/login/login.py
- src/types/packets/login/set_comp.py
- src/types/packets/play/animations.py
- src/types/packets/play/block.py
- src/types/packets/play/boss.py
- src/types/packets/play/chat.py
- src/types/packets/play/cooldown.py
- src/types/packets/play/difficulty.py
- src/types/packets/play/entity.py
- src/types/packets/play/explosion.py
- src/types/packets/play/player.py
- src/types/packets/play/plugin_channels.py
- src/types/packets/play/sounds.py
- src/types/packets/play/spawn.py
- src/types/packets/play/statistics.py
- src/types/packets/play/window.py
- src/types/packets/status/status.py
- src/util/data_gen.py
We should update main branch just in case someone forks from it and uses id_ instead of id
> The .id_ class attribute for packets is updated to .id

- src/types/buffer.py
- src/types/packets/play/advancement.py
- src/types/packets/play/block.py
- src/types/packets/play/chat.py
- src/types/packets/play/command_block.py
- src/types/packets/play/crafting.py
- src/types/packets/play/difficulty.py
- src/types/packets/play/effect.py
- src/types/packets/play/entity.py
- src/types/packets/play/item.py
- src/types/packets/play/player.py
- src/types/packets/play/structure_block.py
- src/types/packets/play/vehicle.py
- src/types/packets/play/window.py
> Add optional field handling methods and remove bool handling methods

- src/types/packets/play/advancement.py
- src/types/packets/play/block.py
- src/types/packets/play/boss.py
- src/types/packets/play/chat.py
- src/types/packets/play/chunk.py
- src/types/packets/play/cooldown.py
- src/types/packets/play/crafting.py
- src/types/packets/play/entity.py
- src/types/packets/play/explosion.py
- src/types/packets/play/map.py
- src/types/packets/play/particle.py
- src/types/packets/play/player.py
- src/types/packets/play/plugin_msg.py
- src/types/packets/play/scoreboard.py
- src/types/packets/play/sign.py
- src/types/packets/play/sounds.py
- src/types/packets/play/spawn.py
- src/types/packets/play/structure_block.py
- src/types/packets/play/time.py
- src/types/packets/play/vehicle.py
- src/types/packets/play/window.py
As stated in the [support server](https://discord.gg/dHjv7DJgb2), benefits include:
1. My commit history being good again
2. Anyone attempting to test it will get the latest version of the code
3. Better for creating new branches later on that deal with changes from `112-play` and `4-create-packets`
> Merge 112-play to main

- plugins/FAP/__init__.py
- pymine/api/__init__.py
- pymine/logic/handle/handshaking.py
- pymine/logic/handle/login.py
- pymine/logic/handle/status.py
- pymine/server.py
- pymine/types/stream.py
- pymine/util/encryption.py
> Merge StreamReader and StreamWriter into a singular Stream object

- pymine/server.py
> Fetch primary local address if addr is None

- pymine/api/__init__.py
- pymine/util/config.py
- pymine/util/misc.py
- Loads all plugins at once via `asyncio.gather()`
- Resolves #205.
> 205 Concurrent Plugin Updating

- CONTRIBUTING.md
the link wont work unless you add https:// else you will be redirected to https://github.com/py-mine/PyMine/blob/main/discord.gg/dHjv7DJgb2
> Ammar sys fixdiscord contributing md

- pymine/types/buffer.py
- pymine/types/chat.py
- pymine/types/packets/play/chat.py
- pymine/types/packets/play/crafting.py
- pymine/types/packets/play/entity.py
- pymine/types/packets/play/player.py
- pymine/types/packets/play/recipe.py
- pymine/types/packets/play/statistics.py
- pymine/types/packets/play/team.py
- pymine/types/packets/play/vehicle.py
- pymine/types/packets/play/villager.py
- pymine/types/packets/play/window.py
- pymine/util/logging.py
> refactor gen comp with .join() to list comp

- pymine/logic/packet/login.py
Gives the send_packet func the stream attribute.
> Fix offline login

- pymine/logic/play.py
- pymine/types/buffer.py
- pymine/types/nbt.py
- pymine/types/packets/play/block.py
- pymine/types/packets/play/chunk.py
- pymine/types/packets/play/entity.py
- pymine/types/packets/play/player.py
- pymine/types/packets/play/scoreboard.py
- requirements.txt
> Update buffer.py and requirements.txt

- pymine/types/buffer.py
> Add modifier handler methods to Buffer of buffer.py

- pymine/types/level.py
changes the import to use our own nbt implementation
> Use our own nbt implementation

- pymine/types/bitfield.py
> add BitField class

- startserver.sh
inspired by the discord
will go through python binarys until it finds a version >= 3.7
and run $command pymine
> Add startup shell script

- pymine/logic/parsers/minecraft/__init__.py
- pymine/logic/parsers/minecraft/player.py
Added command parsing functionality for minecraft UUIDs.
See #266 (``minecraft:uuid``)
> Added UUID command parser

- startserver.ps1
- startserver.sh
[bash] instead of setting the minimun python version everytime, set it outside the for loop
[pwsh] add powershell startup script
[pwsh] add missing quotes
> The456gamer: Update startscripts

- .github/workflows/pytest.yml
also add support for manual running, i used it for testing, but it might be useful?
> speed up pytest github action

- __init__.py
- pymine/api/__init__.py
- pymine/api/abc.py
- pymine/api/events.py
- pymine/api/register.py
- pymine/logic/handle/handshaking.py
- pymine/logic/handle/login.py
- pymine/logic/handle/play/plugin_channels.py
- pymine/logic/handle/play/settings.py
- pymine/logic/handle/play/teleport.py
- pymine/logic/handle/status.py
- pymine/server.py
Resolves #269, adds a discord.py-like structure to PyMine plugins.
> Update plugin structure

- pymine/api/console.py
- pymine/api/console_log_formatter.py
you better merge this after is spent days on this :eyes:
> [wip] Use Python's Logging module

- docs/conf.py
> disable sphinx theme from making flake8 F401 error
